// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANw-V5DfElRGdBZOQHofccWHFis1728fI',
    appId: '1:353195202717:web:32d110f16ab5504b215c74',
    messagingSenderId: '353195202717',
    projectId: 'fruits-ecommerce-2026',
    authDomain: 'fruits-ecommerce-2026.firebaseapp.com',
    storageBucket: 'fruits-ecommerce-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe1tN-So0NXOHVhebPvIVY1XM8-dQlKmQ',
    appId: '1:353195202717:android:b982701d9626e4e1215c74',
    messagingSenderId: '353195202717',
    projectId: 'fruits-ecommerce-2026',
    storageBucket: 'fruits-ecommerce-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4GRreKRpCUyAu3tESIdyb_3wW4aZvfvg',
    appId: '1:353195202717:ios:b2f98a61a61a90b1215c74',
    messagingSenderId: '353195202717',
    projectId: 'fruits-ecommerce-2026',
    storageBucket: 'fruits-ecommerce-2026.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4GRreKRpCUyAu3tESIdyb_3wW4aZvfvg',
    appId: '1:353195202717:ios:b2f98a61a61a90b1215c74',
    messagingSenderId: '353195202717',
    projectId: 'fruits-ecommerce-2026',
    storageBucket: 'fruits-ecommerce-2026.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANw-V5DfElRGdBZOQHofccWHFis1728fI',
    appId: '1:353195202717:web:40fbb7b66a6f08b7215c74',
    messagingSenderId: '353195202717',
    projectId: 'fruits-ecommerce-2026',
    authDomain: 'fruits-ecommerce-2026.firebaseapp.com',
    storageBucket: 'fruits-ecommerce-2026.firebasestorage.app',
  );
}
